---

- name: Configure RabbitMQ for Sensu client
  template:
    src: rabbitmq.json.j2
    dest: /etc/sensu/conf.d/rabbitmq.json
  tags:
    - sensu_config

- name: Create Sensu client config
  template:
    src: client.json.j2
    dest: /etc/sensu/conf.d/client.json
  notify:
    - Restart sensu-client
  tags:
    - sensu_config

- name: Make sure sensu-client is enabled and started
  service:
    name: sensu-client
    enabled: yes
    state: started
