---

- name: Create sensu directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/sensu/ssl
    - /etc/sensu/conf.d

- name: Copy Sensu rabbitmq config file
  template:
    src: rabbitmq.json.j2
    dest: "{{ sensu_config_dir }}/conf.d/rabbitmq.json"

- name: Debug install
  debug: msg="Installing sensu from {{ sensu_repo }}"

- name: Install sensu
  yum:
    name: sensu
    state: present
