---

- name: Sensu distribution is RedHat
  assert:
    that: ansible_os_family == "RedHat" and
          ansible_distribution_major_version | int >= 6 

- include: common.yaml

- include: server.yaml
  when: install_sensu_server

- include: client.yaml
