---

- name: Sensu distribution is RedHat
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int >= 6

- name: Install Sensu
  yum:
    name: "{{ sensu_pkg }}"
    state: present

- include: server.yaml
  when: sensu_install_server

- include: api.yaml
  when: sensu_install_api

- include: client.yaml
  when: sensu_install_client
