---

- name: Sensu server var
  debug: "Sensu server var is {{ install_sensu_server }}"

- name: Copy server config to Sensu SSL dir
  template:
    src: server.json.j2
    dest: "{{ sensu_config_dir }}/config.json"
    owner: root
    group: root
    mode: 644

- name: Copy SSL certs and restart server
  copy:
    src: "{{ item }}.pem"
    dest: "{{ sensu_ssl_dir }}/{{ item }}.pem"
    owner: root
    group: root
    mode: 644
  with_items:
    - client_cert
    - client_key
  notify:
    - restart_sensu_server
    - restart_sensu_api

- name: start_sensu_api
  service:
    name: sensu-api
    enabled: yes
    state: started

- name: start_sensu_server
  service:
    name: sensu-server
    enabled: yes
    state: started
