---

- name: Create Sensu server config
  template:
    src: config.json.j2
    dest: /etc/sensu/config.json
  notify: Restart sensu-server

- name: Make sure Sensu server services are enabled and started
  service:
    name: sensu-server
    enabled: yes
    state: started
