---

- name: Copy server config to Sensu SSL dir
  template:
    src: server.json.j2
    dest: "{{ sensu_config_dir }}/config.json"
    owner: root
    group: root
    mode: 644

- name: Copy SSL certs and restart server
  copy:
    src: "{{ item }}.pem"
    dest: "{{ sensu_ssl_dir }}/{{ item }}.pem"
    owner: root
    group: root
    mode: 644
  with_items:
    - client_cert
    - client_key
  notify:
    - restart_sensu_server
    - restart_sensu_api

- name: Install uchiwa dashboard
  yum:
   name: uchiwa
   state: latest

- name: start_sensu_services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - sensu-server
  - sensu-api
  - uchiwa

