---

- name: Copy server config to Sensu dir
  template:
    src: server.json.j2
    dest: "{{ sensu_config_dir }}/config.json"
    owner: root
    group: root
    mode: 644
  notify:
    restart_sensu_server

- name: start_sensu_services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - sensu-server
  - sensu-api
